# I prefer to keep yml clean and readable without server.port=${SERVER_PORT:8081}.
# Spring boot does not see any diff between 'server.port' and 'SERVER_PORT'.
server:
  port: 8081

spring:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5001/resources
    username: postgres
    password: postgres

song.service.url: http://localhost:8082