# I prefer to keep yml clean and readable without server.port=${SERVER_PORT:8081}.
# Spring boot does not see any diff between 'server.port' and 'SERVER_PORT'.
# Environment variables from compose override those values.
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: resource-service
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5001/resources
    username: postgres
    password: postgres