server:
  port: 8081

spring:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
     ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5001/resources
    username: postgres
    password: postgres

song.service.url: http://localhost:8082